lzc-sdk-version: "0.1"
name: KSpeeder
package: cloud.lazycat.app.kspeeder
version: 0.3.0
description: Docker镜像加速专家
homepage: https://kspeeder.istoreos.com
author: istoreos
application:
  subdomain: kspeeder
  background_task: true
  public_path:
    - /
  routes:
    - /=http://kspeeder:5003/

  ingress:
    - protocol: tcp
      port: 5443
      service: kspeeder

services:
  kspeeder:
    container_name: kspeeder
    image: docker.1ms.run/linkease/kspeeder:0.3.0
    binds:
      - /lzcapp/var/data:/kspeeder-data
      - /lzcapp/var/config:/kspeeder-config
